[package]
name = "support"
edition = { workspace = true }
version = { workspace = true }

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
localizer = { path = "../localizer" }
primitives = { path = "../primitives", features = ["testkit"] }
storage = { path = "../storage" }
streamer = { path = "../streamer" }
