[package]
name = "job_runner"
version ={ workspace = true }
edition = { workspace = true }

[dependencies]
tokio = { workspace = true }

primitives = { path = "../primitives" }
gem_tracing = { path = "../tracing", features = ["sentry"] }
