[package]
name = "job_runner"
version ={ workspace = true }
edition = { workspace = true }

[dependencies]
tokio = { workspace = true }
async-trait = { workspace = true }

gem_tracing = { path = "../tracing" }
