[swift]
prefix = ''

[swift.type_mappings]
"UInt32" = "UInt32"
"UInt64" = "UInt64"
"Int" = "Int"
"Int32" = "Int"
"Int64" = "Int64"
"BigInt" = "String"
"BigUint" = "String"
"DateTime" = "Date"
"Value" = "TransactionMetadata" # Fix later to be adjustable

[kotlin.type_mappings]
"Date" = "Long"
"UInt32" = "Long"
"UInt64" = "Long"
"Int" = "Long"
"Int64" = "Long"
"DateTime" = "SerializedDate"
"Data" = "ByteArray"
"Value" = "String?"
"BigInt" = "String"
"BigUint" = "String"

[typescript.type_mappings]
"DateTime" = "Date"
"Data" = "Uint8Array"
"Value" = "object"
"BigInt" = "BigInteger"
"BigUint" = "BigInteger"
"NaiveDateTime" = "Date"
"AssetId" = "string"
"UInt64" = "BigInteger"
"TransactionId" = "string"
