[swift]
prefix = ''

[swift.type_mappings]
"UInt32" = "UInt64"
"Int32" = "Int"
"BigInt" = "BigInt"
"DateTime" = "Date"
"Value" = "TransactionMetadata" # Fix later to be adjustable

[kotlin.type_mappings]
"Date" = "Long"
"UInt32" = "Long"
"UInt64" = "Long"
"Int" = "Long"
"Int64" = "Long"
"DateTime" = "SerializedDate"
"Data" = "ByteArray"
"Value" = "String?"
"BigInt" = "String"

[typescript.type_mappings]
"DateTime" = "Date"
"Data" = "Uint8Array"
"Value" = "object"
"BigInt" = "BigInteger"
"NaiveDateTime" = "Date"
