[package]
name = "swap_oneinch"
edition = { workspace = true }
version = { workspace = true }

[dependencies]
serde = { workspace = true }
reqwest = { workspace = true }
primitives = { path = "../primitives" }
gem_evm = { path = "../gem_evm" }
