[package]
name = "search_index"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
serde = { workspace = true }

meilisearch-sdk = { version = "0.31.0" }

primitives = { path = "../primitives" }
