[package]
name = "streamer"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
tokio = { workspace = true, features = ["sync", "rt", "time"] }
serde = { workspace = true }
serde_json = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }
strum = { workspace = true }

lapin = { version = "4.0.0" }

gem_tracing = { path = "../tracing" }
primitives = { path = "../primitives" }
