[package]
name = "signer"
version = "1.0.0"
edition = { workspace = true }

[dependencies]
ed25519-dalek = { version = "2.2.0", default-features = false, features = ["std", "zeroize"] }
k256 = { workspace = true }
hex = { workspace = true }
alloy-primitives = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
gem_hash = { path = "../gem_hash" }
zeroize = { version = "1.8.2" }

[dev-dependencies]
