[package]
name = "swap_thorchain"
edition = { workspace = true }
version = { workspace = true }

[dependencies]
serde.workspace = true
reqwest.workspace = true
async-trait.workspace = true

primitives = { path = "../primitives" }
