[package]
name = "gem_client"
version = "0.1.0"
edition = "2021"

[features]
default = []
reqwest = ["dep:reqwest", "dep:tokio"]

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_urlencoded = { workspace = true }
reqwest = { workspace = true, optional = true }
hex = { workspace = true }
tokio = { workspace = true, features = ["time"], optional = true }