[package]
name = "api_connector"
edition = { workspace = true }
version = { workspace = true }

[dependencies]
serde = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
primitives = { path = "../primitives" }
