[package]
name = "gem_hypercore"
version = { workspace = true }
edition = { workspace = true }

[features]
default = []
reqwest = ["gem_client/reqwest"]

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
typeshare = { workspace = true }

gem_client = { path = "../gem_client" }
serde_serializers = { path = "../serde_serializers" }
number_formatter = { path = "../number_formatter" }
primitives = { path = "../primitives" }
chain_traits = { path = "../chain_traits" }