[package]
name = "blockchain"
edition = { workspace = true }
version = { workspace = true }

[dependencies]
typeshare = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }