[package]
name = "gem_polkadot"
version = { workspace = true }
edition = { workspace = true }

[features]
default = ["rpc"]
rpc = [
    "dep:serde_json",
    "dep:serde_serializers",
    "dep:async-trait",
    "dep:gem_client",
    "dep:chain_traits",
    "dep:number_formatter",
    "dep:futures",
    "dep:hex",
    "dep:bs58",
]
reqwest = ["gem_client/reqwest"]
integration_tests = ["rpc", "reqwest"]

[dependencies]
primitives = { path = "../primitives" }
serde = { workspace = true, features = ["derive"] }
num-bigint = { workspace = true }
chrono = { workspace = true, features = ["serde"] }

# Optional RPC dependencies
serde_json = { workspace = true, optional = true }
serde_serializers = { path = "../serde_serializers", optional = true }
async-trait = { workspace = true, optional = true }
gem_client = { path = "../gem_client", optional = true }
chain_traits = { path = "../chain_traits", optional = true }
number_formatter = { path = "../number_formatter", optional = true }
futures = { workspace = true, optional = true }

# Required dependencies for transaction encoding
hex = { workspace = true, optional = true }
bs58 = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
reqwest = { workspace = true }
