[package]
name = "settings"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
serde = { workspace = true }
config = { workspace = true }
serde_serializers = { path = "../serde_serializers" }

[features]
testkit = []
