[package]
name = "gem_stellar"
version = { workspace = true }
edition = { workspace = true }

[features]
default = []
rpc = ["dep:number_formatter", "dep:chrono", "dep:async-trait", "dep:chain_traits", "dep:urlencoding", "dep:futures"]
reqwest = ["gem_client/reqwest"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
primitives = { path = "../primitives" }
num-bigint = { workspace = true }

# Optional dependencies for the rpc feature
number_formatter = { path = "../number_formatter", optional = true }
chrono = { workspace = true, features = ["serde"], optional = true }
async-trait = { workspace = true, optional = true }
chain_traits = { path = "../chain_traits", optional = true }
urlencoding = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
serde_json = { workspace = true }
gem_client = { path = "../gem_client" }
serde_serializers = { path = "../serde_serializers" }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
reqwest = { workspace = true }

[[test]]
name = "provider_balances_test"
test = false
required-features = ["rpc", "reqwest"]
