[package]
name = "gem_stellar"
version = { workspace = true }
edition = { workspace = true }

[features]
default = []
rpc = ["dep:reqwest-middleware", "dep:number_formatter", "dep:chrono"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
primitives = { path = "../primitives" }

# Optional dependencies for the rpc feature
reqwest-middleware = { workspace = true, optional = true, features = ["json"] }
number_formatter = { path = "../number_formatter", optional = true }
chrono = { workspace = true, features = ["serde"], optional = true }
