[package]
name = "settings_chain"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
reqwest = { workspace = true }
reqwest-middleware = { workspace = true }
reqwest-retry = { workspace = true }

primitives = { path = "../primitives" }
gem_chain_rpc = { path = "../gem_chain_rpc" }
gem_solana = { path = "../gem_solana", features = ["rpc"] }
settings = { path = "../settings" }
gem_xrp = { path = "../gem_xrp", features = ["rpc"] }
