[package]
name = "notifications"
edition = { workspace = true }
version = { workspace = true }

[dependencies]
localizer = { path = "../localizer" }
primitives = { path = "../primitives" }
serde_json = { workspace = true }
