[package]
name = "gem_tracing"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
sentry = { version = "0.46.0", default-features = false, features = ["tracing", "reqwest", "rustls", "backtrace", "contexts", "debug-images", "panic", "release-health"], optional = true }
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.20" }

[features]
default = []
sentry = ["dep:sentry"]
